[platformio]
default_envs = seeed_xiao_esp32c6, esp12e

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_two_ota.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DEIDON_MOUNT_CORRECTION=1
    -DTARGET_ESP32C6=1
    -DIMU_BUS=1
build_src_filter = +<*> -<bringup_esp12e.cpp>
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.5
    bblanchon/ArduinoJson@^7.2.0
    links2004/WebSockets@^2.6.1

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_two_ota.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DEIDON_MOUNT_CORRECTION=1
    -DTARGET_ESP32C6=1
    -DIMU_BUS=1
build_src_filter = +<*> -<bringup_esp12e.cpp>
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.5
    bblanchon/ArduinoJson@^7.2.0
    links2004/WebSockets@^2.6.1

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
board_build.ldscript = eagle.flash.4m1m.ld
upload_speed = 115200
monitor_speed = 9600
build_flags =
    -DTARGET_ESP12E=1
    -DSERIAL_BAUD=9600
    -DIMU_BUS=1
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH=1
build_src_filter = +<*> -<bringup_esp12e.cpp>
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.5
    bblanchon/ArduinoJson@^7.2.0
    links2004/WebSockets@^2.6.1

[env:esp12e_bringup]
platform = espressif8266
board = esp12e
framework = arduino
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
board_build.ldscript = eagle.flash.4m1m.ld
upload_speed = 115200
monitor_speed = 9600
build_flags =
    -DTARGET_ESP12E=1
    -DSERIAL_BAUD=9600
build_src_filter = +<bringup_esp12e.cpp>
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.5
