[platformio]
default_envs = seeed_xiao_esp32c6

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_two_ota.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DEIDON_MOUNT_CORRECTION=1
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.5
    bblanchon/ArduinoJson@^7.2.0
    links2004/WebSockets@^2.6.1
